### ISSUE TITLE
Cannot find module ... star.json after updating Meteor to 1.6

### ISSUE THREAD

**Issue by adamgedney** [frozeman/meteor-build-client#47]
I experimented with this package a few weeks ago running node v6.12.2 on OSX with a Meteor version of 1.3. I just updated to Meteor 1.6 and this package no longer works. It was working great before. 

Not sure if the environment has changed on my Mac after the update. I tried it with the current node version, then again after using nvm to update to node v8.8.1, then again after reverting back to v6.12.2. I also tried the global install of the meteor-build-client package as well as with a local install. 

I also found these issues: [#19](https://github.com/frozeman/meteor-build-client/issues/19) and  [#4](https://github.com/frozeman/meteor-build-client/issues/4) so i tried both relative and absolute paths in my script. I get the same result every time I try to build.

I'm just running `meteor-build-client ../client-build` from the app directory. It used to work and generate the client-build folder as a sibling to /app.

I'm getting the star.json error and can't seem to get past it. Do you think this is an environment issue?

I should also add that after the build seems to have finished there is no client-build folder generated. This could be more the issue.

Here's the error, truncated.
`Bundling Meteor app...
Generating the index.html...
{ Error: Cannot find module '/Users/****/Sites/****/public_html/client-build/bundle/star.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
   ...`

**Comment by adamgedney** [comment]
I created a [https://github.com/frozeman/meteor-build-client/pull/48](PR) to allow for the user to pass a flag to prevent meteor-build-client from running meteor build itself. This enables the user to run meteor build themselves, then meteor-build-client looks for the ../build folder generated by Meteor. 

In my issue above, the client-build folder was never being generated, for whatever reason. Maybe a change in fs behavior?

This PR is a workaround and adds some flexibility to this awesome package.

Keep up the good work!

**Comment by dr-dimitru** [comment]
Closing in favor of [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0).
Feel free to reopen issue is not solved in v1
